### ISSUE TITLE
Runtime Crash When Nil Pointers Dereferenced

### ISSUE THREAD

**Issue by jcburley** [jcburley/gostd2joker#10]
E.g.:

```
user=> (require '[joker.go.net.mail :as m])
nil
user=> (m/ParseAddress "<craig@theburleys.net> James Craig Burley")
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b6311]

goroutine 1 [running]:
main.processReplCommand.func1(0xc0006fab40)
	/home/craig/.go/src/github.com/candid82/joker/main.go:120 +0x2e5
panic(0x8ea6a0, 0xf2c4f0)
	/usr/local/go.1.11.2/src/runtime/panic.go:513 +0x1b9
github.com/candid82/joker/std/go/net/mail.parseAddress(0xc0004d6630, 0x29, 0x1, 0x0)
	/home/craig/.go/src/github.com/candid82/joker/std/go/net/mail/mail_native.go:14 +0xe1
github.com/candid82/joker/std/go/net/mail.glob..func1(0xc00076e7d0, 0x1, 0x1, 0xc00076e7d0, 0xc00076e7c0)
	/home/craig/.go/src/github.com/candid82/joker/std/go/net/mail/a_mail.go:18 +0x6a
github.com/candid82/joker/core.Proc.Call(0xb4b4e0, 0xc00076e7d0, 0x1, 0x1, 0xc00076e7d0, 0x1)
	/home/craig/.go/src/github.com/candid82/joker/core/object.go:739 +0x44
github.com/candid82/joker/core.(*CallExpr).Eval(0xc000852000, 0x0, 0x0, 0x0)
	/home/craig/.go/src/github.com/candid82/joker/core/eval.go:274 +0x125
github.com/candid82/joker/core.Eval(0xbbef60, 0xc000852000, 0x0, 0x0, 0x0)
	/home/craig/.go/src/github.com/candid82/joker/core/eval.go:107 +0x9b
main.processReplCommand(0xc000629c60, 0x2, 0xc000629c28, 0xc0006fab40, 0x0)
	/home/craig/.go/src/github.com/candid82/joker/main.go:146 +0x1e5
main.repl(0x2)
	/home/craig/.go/src/github.com/candid82/joker/main.go:180 +0x4a0
main.main()
	/home/craig/.go/src/github.com/candid82/joker/main.go:636 +0xa0d
$
```

**Comment by jcburley** [comment]
Here's the crashing code:

```
func parseAddress(address string) Object {
	res1, res2 := mail.ParseAddress(address)
	res := EmptyVector
	map1 := EmptyArrayMap()
	map1.Add(MakeKeyword("Name"), MakeString((*res1).Name))
	map1.Add(MakeKeyword("Address"), MakeString((*res1).Address))
	res = res.Conjoin(map1)
	res = res.Conjoin(func () Object { if (res2) == nil { return NIL } else { return MakeError(res2) } }())
	return res
}
```

The problem is that `res1` is returned as `nil` if the parse fails (`res2` is returned as an `error`), so the dereference(s) in the `map1.Add()` calls crash.

So, more work needs to be done here.

**Comment by jcburley** [comment]
Note that `try` and `catch` (in calling Joker code) cannot protect against this.

**Comment by jcburley** [comment]
Fixed (yesterday).
